service: serverless-static-website

frameworkVersion: ">=1.57.0"

plugins:
  - serverless-finch
  - serverless-pseudo-parameters
  - serverless-offline
  - serverless-export-env

custom:
  client:
    bucketName: ${self:service}-${opt:stage}-bucket
    distributionFolder: src/frontend
    errorDocument: index.html

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-southeast-2'}
  profile: private
  environment:
    CLIENT_ID: ${ssm:ZipMoney-Client-Id~true}
    CLIENT_SECRET: ${ssm:ZipMoney-Client-Secret~true}
    ZIPMONEY_TENANT_ID: ${ssm:ZipMoney-Tenant-Id~true}
  apiKeys:
    - ${self:service}-${opt:stage}-apikey

package:
  exclude:
    - ./**
    - "!src/**"
    - "!node_modules/**"

functions:
  getProducts:
    handler: src/backend/handler.getProducts
    timeout: 30
    events:
      - http:
          method: get
          path: products/available
          # private: true
