service: serverless-static-website

frameworkVersion: ">=1.57.0"

plugins:
  - serverless-finch
  - serverless-pseudo-parameters
  - serverless-offline
  - serverless-export-env

custom:
  config: ${file(./infra/serverless-${opt:stage}.yml)}
  client:
    bucketName: ${self:service}-${opt:stage}-bucket
    distributionFolder: src/frontend
    errorDocument: index.html

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-southeast-2'}
  profile: Danet
  environment:
    CLIENT_ID: ${ssm:ZipMoney-Client-Id~true}
    CLIENT_SECRET: ${ssm:ZipMoney-Client-Secret~true}
    ZIPMONEY_TENANT_ID: ${ssm:ZipMoney-Tenant-Id~true}
    API_STAGE_URL: ${self:custom.config.stageUrl}
  apiKeys:
    - ${self:service}-${opt:stage}-apikey

package:
  exclude:
    - ./**
    - "!src/**"
    - "!node_modules/**"

functions:
  getProducts:
    handler: src/backend/handler.getProductsHandler
    timeout: 30
    events:
      - http:
          method: get
          path: products/available
          private: true
          cors: true
  getSubscriptions:
    handler: src/backend/handler.getSubscriptionsHandler
    timeout: 30
    events:
      - http:
          method: get
          path: subscriptions
          private: true
          cors: true
  makeOrder:
    handler: src/backend/handler.makeOrderHandler
    timeout: 30
    events:
      - http:
          method: post
          path: products/order
          private: true
          cors: true
  updateSubscription:
    handler: src/backend/handler.updateSubscriptionHandler
    timeout: 30
    events:
      - http:
          method: post
          path: subscriptions
          private: true
          cors: true

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: "ApiGatewayRestApi"
